per_page: 16
max_product_name: 100
max_username: 50
min_username: 6
max_email: 255
max_product_title: 60
min_password: 6
remember_session: "1"
default_quantily: 1
min_quantily: 1
min_customer_name: 10
max_customer_name: 100
min_address: 10
max_address: 255
min_phone: 10
max_phone: 15
